Add 'sbp/domains/lock'
okTurtles/sbp-js pull request #4
Opened 2023-06-26 22:49 UTC by snowteamer

Closes #2

2023-07-04 17:55 UTC, taoeffect requested changes
While the implementation of `'sbp/domains/lock'` seems correct, this PR doesn't actually do any locking, but only gives the appearance of locking domains.

2023-07-04 20:15 UTC, snowteamer commented
My bad, you're right. It seems like I forgot to update `'sbp/selectors/register'` accordingly.

2023-07-07 16:53 UTC, taoeffect approved these changes
Fantastic work @snowteamer!! Thanks for updating the tests too! 😄 

SBP is now one more step closer to perfection! 😁

2023-07-07 16:53 UTC, taoeffect commented on index.js
> +        throw new Error(`SBP: unknown or invalid domain name: ${name}`)
Should probably simplify this error message to `SBP: cannot lock non-existent domain: ${name}`

2023-07-07 16:53 UTC, merged

2023-07-07 17:10 UTC, taoeffect commented on index.js
> +    } else for (const name of typeof domainNameOrNames === 'string' ? [domainNameOrNames] : domainNameOrNames) {
Hmm, this `else` should have a `{` after it, but I'll fix that in a followup.

2023-07-07 17:20 UTC, taoeffect commented on dist/module.mjs
> +      const domainName = domainFromSelector(selector)
This actually breaks line 59 above:

```js
if (selector === `${domain}/_init`) {
```

We both forgot to run `npm run flow` which caught this error.